# Make all figures and tables (some figures have been modified in adobe cs)
library(dplyr)
library(reshape2)
library(ggplot2)
library(beyonce) #devtools::install_github("dill/beyonce")
library(RCurl)
library(RColorBrewer)

# Data
load(here::here("R/DataCleanup/allsardineanchovy_3.RData"))# dataframe: alldat (raw data including NAs for missing years)
load(here::here("R/DataCleanup/RAM_Barange_FAO_States.RData")) # RBF (missing years filled w MARSS states)

# Functions
source(here::here("R/DataCleanup/Fill_NAs_SA.R")) # FillNAs.ts() function
source(here::here("R/WMR/NullModel.R"))
source(here::here("R/PowerAnalysis/Scheuerell_timeseries.R"))


# Test data ---------------------------------------------------------------
filter(alldat,datasource=="Barange" & stock == "California anchovy")
unique(alldat$stock)

# Set palettes  ------------------------------------------------------
# Region palette
pal <- beyonce_palette(18)[2:6]

# Sardine-anchovy palette
sacols <- c("#3288bd","#d53e4f") #blue = sardine, red = anchovy

# Figure 1  ----------------------------------
# This figure is constructed in Adobe CS using the following smaller plots.
simlength <- 150
sa.sim <- get.mds.ts(length= simlength,
                     autocorrs = c(0.7,0.7),
                     rho = 0.1,
                     sds = c(0.8,0.8),
                     driver.period = 50,
                     driver.amp = 0.5,
                     CC = matrix(c(1, -1), ncol = 1))
x <- 1:simlength
y <- t(sa.sim)
shortlen <- 1:50

pdf("Short_ts_example.pdf",width = 5, height = 3,useDingbats = FALSE )
plot(x[shortlen],y[shortlen,1],type='l',lwd=2,ylab="Scaled abundance",xlab="Year")
lines(x[shortlen],y[shortlen,2],col="darkgrey",lwd=2)
dev.off()

# Figure 2: Comparability ---------------------------------------------------------

# This figure is generated by the file DominantTS/Comparability.R

# Figure 3a: MARSS covariances ---------------------------------------------
# This is the plot that shows covariances between dominant sardine-anchovy pairs. 
# The code to do this is in "EstimateCovariance.R"

# Figure 3b: wavelet modulus ratios ----------------------------------------
# Distributions for null vs. observed data

# Load data
obs <- get_obs(dat = RBF,
               dsource = "Barange",
               reg = "California",
               var = "landings")
obstest <- get_wmr(obs$std_anchovy, 
                   obs$std_sardine)

xx <- get_surrogates(obs = obs,nsurrogates = 50) 
nulltest1 = get_wmr(anchovy.ts=xx$Anchovy.surrogates[,1],
                    sardine.ts=xx$Sardine.surrogates[,1])
nulltest2 = get_wmr(anchovy.ts=xx$Anchovy.surrogates[,2],
                    sardine.ts=xx$Sardine.surrogates[,2])


# Functions used here are in the NullModel.R file
giantnull <- get_large_null(dat = RBF,
                            dsource = "Barange",
                            reg = "California",
                            var = "landings",
                            nsims=50)
str(giantnull)

distfig <- function(null, observed, return.dataframe = F){
  #' @description plots a histogram of observed WMRs vs. "null" WMR
  #' @param null is a list of three WMR matrices, each of which represents one time window (from a null surrogate)
  #' @param obs is a list of three WMR matrices, each of which represents one time window (observed time series)
  
  nl <- data.frame(ID = rep(names(null), sapply(null, length)),
                 wmrdens = unlist(null))
  obsl <- data.frame(ID = rep(names(observed), sapply(observed, length)),
                     wmrdens = unlist(observed))
  nl$ID_ord = factor(nl$ID, levels=c('less.than.5','five.ten','ten.plus'))
  obsl$ID_ord = factor(obsl$ID, levels=c('less.than.5','five.ten','ten.plus'))
  
  nl$ID_ord <- recode(nl$ID_ord, less.than.5 = "< 5 yr", five.ten = "5-10 yr",ten.plus="10+ yr" )
  obsl$ID_ord <- recode(obsl$ID_ord, less.than.5 = "< 5 yr", five.ten = "5-10 yr",ten.plus="10+ yr" )
  
  ggplot(nl,aes(x=wmrdens)) + 
    geom_density(fill="grey",colour="darkgrey",alpha=0.5) + 
    geom_density(data=obsl,fill="#41b6c4",colour="#41b6c4",alpha=0.5) +
    facet_wrap(~ID_ord,ncol = 1) +
    ylab("Density") +
    xlab("Wavelet modulus ratio (WMR)") +
    theme_classic(base_size=14)
  
  if(return.dataframe == TRUE){
    nl$nv <- "null"
    obsl$nv <- "obs"
    all <- dplyr::bind_rows(nl,obsl)
    return(all)
  }
}

test <- distfig(null = giantnull,observed = obstest,return.dataframe = T)

# Need to get data into the following format for analysis:
# Year Sardine.est Anchovy.est      region datasource variable
newmelt <- alldat %>%  
  select(datasource,stock,year,ssb,rec,landings,sp, region, subregion) %>%  
  melt(id.vars = c("datasource","stock","region", "subregion","year"))


# Get a giant dataframe of all the WMRs for each of the regions.
stocks <- alldat %>% 
  distinct(sp, stock, region, datasource) # get unique stock-region combos
n <- nrow(stocks) # there should be 15 combos of region and datasource

compares <- alldat %>% 
  distinct(region, datasource)


# Landings ----------------------------------------------------------------
landings.wmrs <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
  obs <- get_obs(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "landings")
  obstest <- get_wmr(obs$std_anchovy, obs$std_sardine)
  giantnull <- get_large_null(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "landings",nsims=50)
  null=giantnull
  observed=obstest
  test <- distfig(null = giantnull,observed = obstest,return.dataframe = T)
  test$region <- compares$region[s]
  test$datasource <- compares$datasource[s]
  test$variable <- "landings"
  # NEED TO ADD THESE OR SIMILAR TO FIND OUT WHICH TWO STOCKS ARE BEING COMPARED
  #test$sardstock <- subset(stocks,region==compares$region[s] & datasource==compares$datasource[s] & sp =="Sardine")$stock
  #test$anchstock <- subset(stocks,region==compares$region[s] & datasource==compares$datasource[s] & sp =="Anchovy")$stock
  landings.wmrs <- rbind(landings.wmrs,test)
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


# Biomass -----------------------------------------------------------------
ssb.wmrs <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
    obs <- get_obs(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "ssb")
    obstest <- get_wmr(obs$std_anchovy, obs$std_sardine)
    giantnull <- get_large_null(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "ssb",nsims=50)
    null=giantnull
    observed=obstest
    test <- distfig(null = giantnull,observed = obstest,return.dataframe = T)
    test$region <- compares$region[s]
    test$datasource <- compares$datasource[s]
    test$variable <- "ssb"
    ssb.wmrs <- rbind(ssb.wmrs,test)
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# Rec -----------------------------------------------------------------
rec.wmrs <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
    obs <- get_obs(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "rec")
    obstest <- get_wmr(obs$std_anchovy, obs$std_sardine)
    giantnull <- get_large_null(dat = RBF,dsource = compares$datasource[s],reg = compares$region[s],var = "rec",nsims=50)
    null=giantnull
    observed=obstest
    test <- distfig(null = giantnull,observed = obstest,return.dataframe = T)
    test$region <- compares$region[s]
    test$datasource <- compares$datasource[s]
    test$variable <- "rec"
    rec.wmrs <- rbind(rec.wmrs,test)
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}





# Figure 3b_top ---------------------------------------------------------------
#pdf(file.path(figwd,"Fig5A_landings.pdf"),width = 8,height = 10)
landings.wmrs %>% subset(datasource=="Barange" & nv=="obs") %>% 
  ggplot(aes(x=wmrdens,colour=region,fill=region)) + 
  geom_density(alpha=0.5,lwd=1.2,trim=F) + 
  scale_colour_manual(values=pal) +
  scale_fill_manual(values=pal) +
  facet_wrap(~ID_ord,nrow=1,scales = "free_y") +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  ggtitle("Landings")
#dev.off()


# Figure 3b_bottom ---------------------------------------------------------------
ssb.wmrs %>% subset(datasource=="Barange" & nv=="obs") %>% 
  ggplot(aes(x=wmrdens,colour=region,fill=region)) + 
  geom_density(alpha=0.5,lwd=1.2,trim=F) + 
  scale_colour_manual(values=pal) +
  scale_fill_manual(values=pal) +
  facet_wrap(~ID_ord,nrow=1,scales = "free_y") +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  scale_y_reverse() +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  ggtitle("Biomass")


# Figure 4: P(Type I error) -----------------------------------------------
# This figure is produced by code in R/PowerAnalysis/PowerAnalysis.R

# ESM ---------------------------------------------------------------------

# TABLE S2: Datasets included in the analysis -----------------------------
load(here::here("R/DataCleanup/allsardineanchovy_3.RData"))
studydata <- alldat %>% 
  melt(id.vars=c("datasource","scientificname","stock","year","sp","region","subregion")) %>%
  filter(!is.na(value))

ns <- studydata %>% distinct(datasource,stock,sp,region,variable)
tables1 <- dcast(ns,datasource+stock+sp+region~variable,fun.aggregate = length)
write.csv(tables1,"TableS1.csv")

# TABLE S4: Test for difference in WMR distributions -----------------------
# Perform tests with full null accross each combination of datasource, region, variable
compares.RBF <- RBF %>% distinct(region, datasource, variable) # get unique comparisons

# make table results from Wilcoxon-Mann-Whitney test comparing observed vs null WMRs
test.table <- vector()
for(s in 1:nrow(compares.RBF)){ 
  giantnull <- get_large_null(dat = RBF,dsource = compares.RBF$datasource[s],reg = compares.RBF$region[s],
                              var = compares.RBF$variable[s],nsims=50)
  test <- test_wmr(obs = get_obs(dat = RBF,dsource = compares.RBF$datasource[s],reg = compares.RBF$region[s],
                                 var = compares.RBF$variable[s]), null.combined = giantnull)
  test$region <- compares.RBF$region[s]
  test$datasource <- compares.RBF$datasource[s]
  test$variable <- compares.RBF$variable[s]
  test.table <- rbind(test.table,test)
}

test.table.out <- test.table %>% 
  select(region, variable, datasource, period, U, N, p = p.value, d = diff, CI.L, CI.U, r = r_p)

test.table.out$period <- recode(test.table.out$period, 
                                less.than.5 = "< 5 yr", 
                                five.ten = "5-10 yr", 
                                ten.plus="10+ yr")
test.table.out$p <- round(test.table.out$p, 3)
test.table.out$p[test.table.out$p < 0.001] <- "< 0.001"
test.table.out$d <- round(test.table.out$d, 3)
test.table.out$CI.L <- round(test.table.out$CI.L, 3)
test.table.out$CI.U <- round(test.table.out$CI.U, 3)
test.table.out$r <- round(test.table.out$d, 2)
#test.table.out$r[test.table.out$r > 0 & test.table.out$r < 0.01] <- "< 0.01"
test.table.out <- arrange(test.table.out, region, datasource, variable)

write.csv(test.table.out, file = here::here("Figures/TableS1_test_WMR.csv"))

# Figure S1: Raw time series ------------------------------------------
mf <- melt(alldat,id.vars = c("datasource", "scientificname", "stock", "year", "sp", "region", "subregion"))
mf$variable <- recode(mf$variable,
                      ssb="Biomass",
                      rec="Recruitment",
                      landings="Landings")
mf.new <- mf

figs1 <- mf.new %>%
  group_by(datasource,scientificname,stock,sp,region,subregion,variable) %>% 
  mutate(std.value=value/mean(value,na.rm=T)) %>% #as.data.frame() value/mean(value,na.rm=T)
  filter(std.value<15) %>% 
  filter(variable %in% c("Biomass","Recruitment","Landings"))  %>%
  mutate(variable_f = factor(variable, levels=c("Landings","Biomass","Recruitment"))) %>%
  ggplot(aes(x=year,y=std.value,colour=sp,lty=datasource,group=stock)) +
  scale_linetype_manual("Data source",values=c(1,2,3)) +
  geom_line(lwd=0.6) +
  scale_color_manual("",values=sacols) +
  facet_grid(variable_f~region,scales="free_y") +
  ylab("Standardized value") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) 

medians <- mf.new %>% 
  group_by(datasource,scientificname,stock,sp,region,subregion,variable) %>% 
  filter(variable == "Biomass") %>%
  summarize(medB = median(value,na.rm=T))

figs1.5 <- mf.new %>%
  group_by(datasource,scientificname,stock,sp,region,subregion,variable) %>% 
  filter(variable %in% c("Biomass","Recruitment","Landings"))  %>%
  mutate(variable_f = factor(variable, levels=c("Landings","Biomass","Recruitment"))) %>%
  filter(variable == "Biomass") %>%
  ggplot(aes(x=year,y=value,colour=sp,lty=datasource,group=stock)) +
  scale_linetype_manual("Data source",values=c(1,2,3)) +
  geom_line(lwd=0.6) +
  scale_color_manual("",values=sacols) +
  facet_grid(variable_f~region,scales="free_y") +
  ylab("Value") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  geom_hline(data=medians,aes(yintercept =medB ,colour=sp,lty=datasource))

medians.l <- mf.new %>% 
  group_by(datasource,scientificname,stock,sp,region,subregion,variable) %>% 
  filter(variable == "Biomass") %>%
  summarize(medL = median(value,na.rm=T))

figs1.6 <- mf.new %>%
  group_by(datasource,scientificname,stock,sp,region,subregion,variable) %>% 
  filter(variable %in% c("Biomass","Recruitment","Landings"))  %>%
  mutate(variable_f = factor(variable, levels=c("Landings","Biomass","Recruitment"))) %>%
  filter(variable == "Landings") %>%
  ggplot(aes(x=year,y=value,colour=sp,lty=datasource,group=stock)) +
  scale_linetype_manual("Data source",values=c(1,2,3)) +
  geom_line(lwd=0.6) +
  scale_color_manual("",values=sacols) +
  facet_grid(variable_f~region,scales="free_y") +
  ylab("Value") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  geom_hline(data=medians.l,aes(yintercept =medL ,colour=sp,lty=datasource))

pdf(here::here("R/Figures/Fig1_S1.pdf"),width = 12, height = 7,useDingbats = F)
figs1 
dev.off()



# Figure S2: Schematic of spectral analysis --------------------------------
# Follows from Fig 1
scale.exp = 0.5; nscales = get.nscales(x)
min.scale = get.min.scale(x); max.scale = get.max.scale(x)
scales = log2Bins(min.scale, max.scale, nscales)
w = mvcwt(x, y)
mr = wmr(w)

pdf("Contour_Example.pdf",useDingbats = FALSE,width = 6,height=5)
image(mr)
dev.off()

#Other pieces
pdf("Contour_Example_ts.pdf",useDingbats = FALSE,width = 4,height=8)
par(mfrow=c(4,1))
plot(x,y[,1],type='l',lwd=2,ylab="Scaled abundance",xlab="Year")
lines(x,y[,2],col="darkgrey",lwd=2)
legend("topright",legend=c("Sardine","Anchovy"),lwd=c(2,2),col=c("black","darkgrey"),bty='n')
wmrs <- get_wmr(anchovy.ts = y[,1],sardine.ts = y[,2])
for(i in 1:3){
  hist(wmrs[[i]],main='',freq = FALSE,col="lightgrey",border="lightgrey",xaxt="n",xaxs="i",yaxs="i",xlab="",ylab="")
  d <- density(wmrs[[i]],na.rm=T)
  lines(d,lwd=2)
}
axis(1,xlim=c(0,1),xaxs="i")
dev.off()





figS3 <- alldat %>%
  filter(datasource == "Barange") %>% #" & stock %in% dom.by.median$stock) %>%
  select(datasource,stock,year,ssb,rec,landings,totalcatch, sp,region,subregion) %>%
    reshape2::melt(id.vars=c('datasource','stock','year','sp','region','subregion')) %>%
    filter(variable != "totalcatch") %>%
    group_by(stock,sp,region,variable) %>%
    summarize(medians = median(value,na.rm = T)) %>%
    mutate(variable = recode_factor(variable, fishing.mortality="Fishing mortality",
                          ssb="Spawning \n stock biomass",
                          landings="Landings",
                          rec="Recruitment")) %>%
    ggplot(aes(x=stock,y=medians,fill=sp)) +
    geom_bar(stat = "identity") +
    scale_fill_manual("Species",values=sacols) +
    facet_grid(variable ~ region,scales='free') +
    theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) +
    ylab("Median value") +
    xlab("Stock") +
    theme(axis.text.x = element_text(angle = 60,hjust=1)) +
    ggtitle("Barange et al. 2009") +
    theme(plot.margin = unit(c(0,0,0,2), "cm"))

tiff(filename = "FigureS3.tiff",width = 8,height = 10,units = 'in',res = 150)
figS3
dev.off()

figS4 <- alldat %>%
  filter(datasource == "FAO") %>% #" & stock %in% dom.by.median$stock) %>%
  select(datasource,stock,year,landings,sp,region,subregion) %>%
  reshape2::melt(id.vars=c('datasource','stock','year','sp','region','subregion')) %>%
  filter(variable != "totalcatch") %>%
  group_by(stock,sp,region,variable) %>%
  summarize(medians = median(value,na.rm = T)) %>%
  mutate(variable = recode_factor(variable, fishing.mortality="Fishing mortality",
                                  ssb="Spawning \n stock biomass",
                                  landings="Landings",
                                  rec="Recruitment")) %>%
  ggplot(aes(x=stock,y=medians,fill=sp)) +
  geom_bar(stat = "identity") +
  scale_fill_manual("Species",values=sacols) +
  facet_grid(variable ~ region,scales='free') +
  theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) +
  ylab("Median value") +
  xlab("Stock") +
  theme(axis.text.x = element_text(angle = 60,hjust=1)) +
  ggtitle("FAO (landings)") +
  theme(plot.margin = unit(c(0,0,0,2), "cm"))

tiff(filename = "FigureS4.tiff",width = 8,height = 6,units = 'in',res = 150)
figS4
dev.off()

figS5 <- alldat %>%
  filter(datasource == "RAM") %>% #" & stock %in% dom.by.median$stock) %>%
  select(datasource,stock,year,ssb,rec,landings,totalcatch, sp,region,subregion) %>%
  reshape2::melt(id.vars=c('datasource','stock','year','sp','region','subregion')) %>%
  filter(variable != "landings") %>%
  group_by(stock,sp,region,variable) %>%
  summarize(medians = median(value,na.rm = T)) %>%
  mutate(variable = recode_factor(variable, fishing.mortality="Fishing mortality",
                                  ssb="Spawning \n stock biomass",
                                  totalcatch="Total catch",
                                  rec="Recruitment")) %>%
  ggplot(aes(x=stock,y=medians,fill=sp)) +
  geom_bar(stat = "identity") +
  scale_fill_manual("Species",values=sacols) +
  facet_grid(variable ~ region,scales='free') +
  theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) +
  ylab("Median value") +
  xlab("Stock") +
  theme(axis.text.x = element_text(angle = 60,hjust=1)) +
  ggtitle("RAM legacy") +
  theme(plot.margin = unit(c(0,0,0,2), "cm"))

tiff(filename = "FigureS5.tiff",width = 10,height = 7,units = 'in',res = 150)
figS5
dev.off()

# load(here::here("R/Replaceability/Replacement_RAM_Barange_MEDIAN.Rdata")) #df: Both
# # Don't have max landings from RAM, probably because they weren't used for replaceability?
# 
# Both$variable <- recode(Both$variable,
#                         fishing.mortality="Fishing mortality",
#                         ssb="Spawning \n stock biomass",
#                         landings="Landings",
#                         rec="Recruitment")
# 
# cleanup_stocks <- c("Engraulidae - Atlantic, Southeast",
#                     "Round sardinella - Atlantic, Southeast",
#                     "California anchovy - Pacific, Northeast",
#                     "Engraulidae - Pacific, Northwest",
#                     "Sardinella spp - Pacific, Northwest",
#                     "Slender raindbow sardine - Pacific, Northwest",
#                     "Stolephorus spp - Pacific, Northwest",
#                     "Sardinella spp - Atlantic, Northeast")
# 
# # Need to remove time series that aren't the "dominant" stocks in that ecosystem
# remove.x <- vector()
# for(i in 1:nrow(Both)){
#   if(Both$stock[i] %in% c(Both$domsard[i],Both$domanch[i])){
#     remove.x[i] = T}else{remove.x[i] = F} 
# }
# Both <- Both[remove.x,]
# 
# figS2 <- 
#   Both %>% 
#   filter(!stock %in% cleanup_stocks) %>%
#   filter(datasource=="FAO") %>%
#   filter(variable=="Landings") %>%
#   droplevels() %>%
#   ggplot(aes(x=stock,y=median.var,fill=sp)) +
#   geom_bar(stat = "identity") + 
#   scale_fill_manual("Species",values=sacols) +
#   facet_grid(variable~region,scales='free') +
#   theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) + 
#   xlab("Dominant stock") +
#   ylab("Median landings") +
#   theme(axis.text.x = element_text(angle = 60,hjust=1)) +
#   ggtitle("FAO landings") +
#   theme(plot.margin = unit(c(0,0,0,2), "cm"))
# 
# pdf(file.path(here::here("R","Figures","FAO_medians.pdf")),width = 11, height=7,useDingbats = F)
# figS2
# dev.off()
# 
# 
# figS3 <- Both %>% 
#   filter(!stock %in% cleanup_stocks) %>%
#   filter(datasource=="RAM" & variable == "Spawning \n stock biomass" ) %>%
#   filter(variable != "Recruitment") %>%
#   droplevels() %>%
#   ggplot(aes(x=stock,y=median.var,fill=sp)) +
#   geom_bar(stat = "identity") + 
#   scale_fill_manual("Species",values=sacols) +
#   facet_wrap(region~variable,scales='free') +
#   theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) + 
#   xlab("Dominant stock ") +
#   ylab("Median biomass") +
#   theme(axis.text.x = element_text(angle = 60,hjust=1)) +
#   ggtitle("RAM") +
#   theme(plot.margin = unit(c(0,0,0,2), "cm"))
# 
# figS3
# 
# tiff(here::here("R/Figures/RAM_medians.tiff"),width = 7, height=6,units = 'in',res = 250)
# figS3
# dev.off()
# 
# figS3 <- Both %>%  #now Barange
#   filter(!stock %in% cleanup_stocks) %>%
#   filter(datasource=="Barange") %>%
#   droplevels() %>%
#   ggplot(aes(x=stock,y=median.var,fill=sp)) +
#   geom_bar(stat = "identity") + 
#   scale_fill_manual("Species",values=sacols) +
#   facet_grid(variable~region,scales='free') +
#   theme_classic(base_size=14)%+replace% theme(strip.background  = element_blank()) + 
#   xlab("Dominant stock ") +
#   ylab("Median value") +
#   theme(axis.text.x = element_text(angle = 60,hjust=1)) +
#   ggtitle("Barange et al. (2009)") +
#   theme(plot.margin = unit(c(0,0,0,2), "cm"))
# 
# figS3
# 
# tiff(here::here("R/Figures/Barange_medians.tiff"),width = 8, height=8,units = 'in',res = 250)
# figS3
# dev.off()

# Figure S4: Observed and null WMRs, landings ---------------------------------------
std.landings <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
    obs <- get_obs(dat = RBF,
                   dsource = compares$datasource[s],
                   reg = compares$region[s],var = "landings")
    df.obs <- data.frame(Anchovy = obs$std_anchovy,
                         Sardine = obs$std_sardine,
                         region = compares$region[s],
                         datasource = compares$datasource[s],
                         Time = 1:length(obs$std_anchovy)
                         )
    std.landings <- bind_rows(std.landings,df.obs) 
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

pd <- melt(std.landings,id.vars = c("region","datasource","Time"))
pd <- pd[-1,]

figS4a <- 
  pd %>% filter(datasource=="Barange") %>%
  ggplot(aes(x=Time,y=value,colour=variable)) + 
  geom_line(lwd=1) +
  scale_colour_manual("",values=c("black","grey")) +
  facet_wrap(~region,nrow = 1) +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  ylab("Standardized landings")+
  ggtitle("Landings")

figS4b <- landings.wmrs %>% subset(datasource=="Barange") %>% 
  ggplot(aes(x=wmrdens,colour=region,lty=nv,alpha=nv)) + 
  geom_density(alpha=0.5,lwd=1,trim=F) + 
  scale_colour_manual(values=pal) +
  scale_linetype_manual("",values=c("dashed", "solid"))+
  facet_grid(ID_ord~region,scales = "free_y") +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) 


tiff(here::here("R/Figures/FigureS4_WMRobsnull_landings.tiff"),width = 11,height = 7,res=250,units = 'in')
grid.arrange(figS4a,figS4b)
dev.off()


# FIGURE S5:Observed and null WMRs, biomass --------------------------------------

std.biomass <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
    obs <- get_obs(dat = RBF,
                   dsource = compares$datasource[s],
                   reg = compares$region[s],var = "ssb")
    df.obs <- data.frame(Anchovy = obs$std_anchovy,
                         Sardine = obs$std_sardine,
                         region = compares$region[s],
                         datasource = compares$datasource[s],
                         Time = 1:length(obs$std_anchovy)
    )
    std.biomass <- bind_rows(std.biomass,df.obs) 
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

pd <- melt(std.biomass,id.vars = c("region","datasource","Time"))
pd <- pd[-1,]

figS5a <- 
  pd %>% filter(datasource=="Barange") %>%
  ggplot(aes(x=Time,y=value,colour=variable)) + 
  geom_line(lwd=1) +
  scale_colour_manual("",values=c("black","grey")) +
  facet_wrap(~region,nrow = 1) +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  ylab("Standardized biomass")+
  ggtitle("Biomass")
figS5a

figS5b <- ssb.wmrs %>% subset(datasource=="Barange") %>% 
  ggplot(aes(x=wmrdens,colour=region,lty=nv,alpha=nv)) + 
  geom_density(alpha=0.5,lwd=1,trim=F) + 
  scale_colour_manual(values=pal) +
  scale_linetype_manual("",values=c("dashed", "solid"))+
  facet_grid(ID_ord~region,scales = "free_y") +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) 

grid.arrange(figS5a,figS5b)

tiff(here::here("R/Figures/FigureS5_WMRobsnull_biomass.tiff"),width = 11,height = 7,res=250,units = 'in')
grid.arrange(figS5a,figS5b)
dev.off()

# FIGURE S6:Observed and null WMRs, recruitment ----------------------------

std.rec <- vector()
for(s in 1:nrow(compares)){ 
  tryCatch ({
    obs <- get_obs(dat = RBF,
                   dsource = compares$datasource[s],
                   reg = compares$region[s],var = "rec")
    df.obs <- data.frame(Anchovy = obs$std_anchovy,
                         Sardine = obs$std_sardine,
                         region = compares$region[s],
                         datasource = compares$datasource[s],
                         Time = 1:length(obs$std_anchovy)
    )
    std.rec <- bind_rows(std.rec,df.obs) 
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

pd <- melt(std.rec,id.vars = c("region","datasource","Time"))
pd <- pd[-1,]

figS6a <- 
  pd %>% filter(datasource=="Barange") %>%
  ggplot(aes(x=Time,y=value,colour=variable)) + 
  geom_line(lwd=1) +
  scale_colour_manual("",values=c("black","grey")) +
  facet_wrap(~region,nrow = 1) +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) +
  ylab("Standardized recruitment")+
  ggtitle("Recruitment")
figS6a

figS6b <- rec.wmrs %>% subset(datasource=="Barange") %>% 
  ggplot(aes(x=wmrdens,colour=region,lty=nv,alpha=nv)) + 
  geom_density(alpha=0.5,lwd=1,trim=F) + 
  scale_colour_manual(values=pal) +
  scale_linetype_manual("",values=c("dashed", "solid"))+
  facet_grid(ID_ord~region,scales = "free_y") +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  ylim(c(0,10)) +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) 

grid.arrange(figS6a,figS6b)

tiff(here::here("R/Figures/FigureS6_WMRobsnull_recruitment.tiff"),width = 11,height = 7,res=250,units = 'in')
grid.arrange(figS6a,figS6b)
dev.off()



# Reviewer questions ---------------------------------------

# How many values are replaced when MARSS states are used to fill missing values for WMR?
test.est <- subset(RBF, region=="Benguela" & datasource=="Barange" &variable=="ssb")
test.obs <- subset(alldat,region=="Benguela" & datasource=="Barange" ) %>% select(datasource,stock,year,ssb) 


split.sa <- test.obs %>% group_by(stock) %>%group_split() 
grep("anch",split.sa[[1]]$stock)
split.sa

anch.obs <- split.sa[[2]] %>% as.data.frame()
sard.obs <- split.sa[[1]] %>% as.data.frame()


par(mfrow=c(1,2))
anch.est <- test.est %>% select(Year,Anchovy.est,region,datasource,variable)
tga <- merge(anch.obs,anch.est,all.y = T,by.x = "year",by.y = "Year" )
startcount <- min(which(!is.na(tga$ssb)))
length(which(is.na(tga$ssb[startcount:nrow(tga)])))
plot(anch.obs$year,anch.obs$ssb,xlab="year",ylab="SSB",main="Anchovy")
lines(anch.est$Year,anch.est$Anchovy.est)

sard.est <- test.est %>% select(Year,Sardine.est,region,datasource,variable)
tgs <- merge(sard.obs,sard.est,all.y = T,by.x = "year",by.y = "Year" )
startcount <- min(which(!is.na(tgs$ssb)))
length(which(is.na(tgs$ssb[startcount:nrow(tgs)])))
plot(sard.obs$year,sard.obs$ssb,xlab="year",ylab="SSB",main="Sardine")
lines(sard.est$Year,sard.est$Sardine.est)
legend("topleft",legend = c("est","obs"),pch=c(NA,1),lty=c(1,0))


# Leftovers ---------------------------------------------------------------
# Figure XXX for a demo in Fig 1
fig2_wmr <- landings.wmrs %>% subset(datasource=="Barange") %>% 
  filter(region=="NE Atlantic" & ID == "five.ten") %>%
  ggplot(aes(x=wmrdens,colour=region,fill=nv)) + 
  geom_density(lwd=1,trim=FALSE,colour="black",alpha=0.5) + 
  scale_fill_manual("",values=c("black","yellow")) +
  ylab("Density") +
  xlab("Wavelet modulus ratio (WMR)") +
  theme_classic(base_size=14) %+replace% theme(strip.background  = element_blank()) 

pdf("Fig2_wmr_example.pdf",width = 4, height = 2,useDingbats = FALSE)
fig2_wmr
dev.off()
